// GET READ
// POST CREATE
// PUT UPDATE 전체 수정
// PATCH UPDATE 부분 수정
// DELETE


GET http://localhost:3003/posts HTTP/1.1
Content-Type: application/json; charest=UTF-8

###

POSt http://localhost:3003/posts/ HTTP/1.1
Content-Type: application/json; charest=UTF-8

{
    "id": "2",
    "title": "new title 2",
    "views": 200
}

###

PUT http://localhost:3003/posts/1 HTTP/1.1
Content-Type: application/json; charest=UTF-8

{
    "id": "1",
    "title": "new title 1",
    "views": 100
}
